### ISSUE TITLE
css animation and transform

### ISSUE THREAD

**Issue by lfb** [liangfengbo/css-layout#1]
文章大纲：
- css3 animation 动画
    - @keyframes 关键帧
    - animation 动画属性
- css3 transform 变形
    - translate(x, y) 移动x，y轴的位置
    - translateX(x) 移动X轴值
    - translateY(y) 移动Y轴值
    - scale(x, y) 2D下缩放
    - scaleX(x) 设置 X 轴的值来定义缩放转换
    - scaleY(y) 设置 Y 轴的值来定义缩放转换
    - rotate(angle) 定义 2D 旋转，在参数中规定角度
    - rotate3d(x,y,z,angle) 定义 3D 旋转
    - rotateX(angle) 定义沿着 X 轴的 3D 旋转
    - rotateY(angle) 定义沿着 Y 轴的 3D 旋转
    - rotateZ(angle) 定义沿着 Z 轴的 3D 旋转
    - skew(x-angle, y-angle)	定义沿着 X 和 Y 轴的 2D 倾斜转换
    - skewX(angle)	定义沿着 X 轴的 2D 倾斜转换
    - skewY(angle)	定义沿着 Y 轴的 2D 倾斜转换

## 一、@keyframes 关键帧
- 通过 `@keyframes` 规则，您能够创建动画。
- 创建动画的原理是，将一套 CSS 样式逐渐变化为另一套样式。
- 在动画过程中，您能够多次改变这套 CSS 样式。
- 以百分比来规定改变发生的时间，或者通过关键词 "from" 和 "to"，等价于 0% 和 100%。
- 0% 是动画的开始时间，100% 动画的结束时间。
- 为了获得最佳的浏览器支持，您应该始终定义 0% 和 100% 选择器

语法：
- `animationname` 必填 定义动画名字
- `keyframes-selector` 必填 动画时长的百分比
    - 0-100%
    - from（0） ~ to （100%）

```css
@keyframes animationname {keyframes-selector {css-styles;}}
```

实例：

```css
@keyframes changeColorAnimate {
    0% { background: red }
    25% { background: blue }
    50% { background: green }
    75% { background: yellow }
    100% { background: pink }
}

@keyframes changeColorAnimate2 {
    from { background: red }
    to { background: blue }
}
```

## 二、animation 动画属性
- 作用是定义了 `@keyframes` 规则，然后使用 `animation` (动画属性) 绑定一个元素样式上，执行动画。

动画属性：

属性 | 描述
---|---
@keyframes | 规定动画
animation | 所有动画属性的简写属性，除了 animation-play-state 属性
animation-name | 规定 @keyframes 动画的名称
animation-duration | 规定动画完成一个周期所花费的秒或毫秒。默认是 0 
animation-delay | 规定动画何时开始。默认是 0 | 单位(s)或毫秒
animation-iteration-count | 规定动画被播放的次数。默认是 1；无限循环播放：infinite
animation-direction | 规定动画是否在下一周期逆向地播放。默认是正常播放 "normal"；<br>动画应该轮流反向播放：alternate
animation-play-state | 规定动画是否正在运行或暂停。默认是规定动画正在播放 "running；<br>规定动画已暂停：paused
animation-fill-mode | 规定对象动画时间之外的状态，none，forwards，backwards，both
animation-timing-function | 规定动画的速度曲线。默认是 ease(慢-快-慢) <br>linear（均速）<br>ease-in（慢开始）<br>ease-out（慢结束）<br>ease-in-out（开始和结尾都慢）<br>cubic-bezier(n,n,n,n)

实例

```css
.box {
    position: absolute;
    width: 100px;
    height: 100px;
    background: red;
    /*动画名称*/
    animation-name: changeColorAnimate;
    /*规定时间内完成动画*/
    animation-duration: 2.5s;
    /*动画开始时间*/
    animation-delay: 0s;
    /*播放次数*/
    animation-iteration-count: infinite;
    /*动画下一周期是否逆向播放*/
    animation-direction: alternate;
    /*动画的速度曲线*/
    animation-timing-function: ease-in-out;
    
    /* 简写：动画的名字，播放时间，延时时间，动画效果，播放次数，播放顺序*/
    /*animation: changeColorAnimate 2.5s 0s ease-in-out infinite alternate;*/
}

/*关键帧*/
@keyframes changeColorAnimate {
    0% {
        background: red
    }
    25% {
        background: blue
    }
    50% {
        background: green
    }
    75% {
        background: yellow
    }
    100% {
        background: pink
    }
}
```

## 三、translate(x, y) 移动x，y轴的位置
- translateX(x) X轴值
- translateY(y) Y轴值
 
```css
/*向x,y轴进行各移动100px*/
transform: translate(100px, 200px);

/*向x轴进行各移动100px*/
transform: translateX(100px);
/*向y轴进行各移动100px*/
transform: translateY(100px);
```

## 四、scale(x, y) 2D下缩放
- scaleX(x) 设置 X 轴的值来定义缩放转换
- scaleY(y) 设置 Y 轴的值来定义缩放转换

```css
/*宽度不变，高度缩小一半*/
transform: scale(1, 0.5);
/*宽高度各放大2倍*/
transform: scale(2, 2);
/*宽度缩小一半*/
transform: scaleX(0.5);
/*高度放大一倍*/
transform: scaleY(2);
```

## 五、rotate(angle) 定义 2D 旋转，在参数中规定角度
- rotate3d(x,y,z,angle) 定义 3D 旋转
- rotateX(angle) 定义沿着 X 轴的 3D 旋转，从下向上旋转
- rotateY(angle) 定义沿着 Y 轴的 3D 旋转，从左向右旋转
- rotateZ(angle) 定义沿着 Z 轴的 3D 旋转，以方框中心为原点，顺时针旋转

```css
/*2D下旋转45deg*/
transform: rotate(45deg);

/*沿着 X 轴旋转*/ 
transform: rotateX(45deg);
/*沿着 Y 轴旋转*/ 
transform: rotateY(45deg);
/*沿着 Z 轴旋转*/ 
transform: rotateZ(45deg);
```

## 六、skew(x-angle, y-angle)	定义沿着 X 和 Y 轴的 2D 倾斜转换
- skewX(angle)	定义沿着 X 轴的 2D 倾斜转换(逆时针倾斜)
- skewY(angle)	定义沿着 Y 轴的 2D 倾斜转换(顺时针针倾斜)

```css
.box {
    width: 200px;
    height: 200px;
    background: #f00;
    animation: myAnimation 4s 0s linear infinite normal;
}

@keyframes myAnimation {
    0% {
        transform: skewY(0deg)
    }
    12.5% {
        transform: skewY(45deg)
    }
    25% {
        transform: skewY(90deg)
    }
    37.5% {
        transform: skewY(135deg)
    }
    50% {
        transform: skewY(180deg)
    }
    62.5% {
        transform: skewY(225deg)
    }
    75% {
        transform: skewY(270deg)
    }
    87.5% {
        transform: skewY(315deg)
    }
    100% {
        transform: skewY(360deg)
    }
}
```
